[package]
name = "postgres-derive-test"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2024"
rust-version = "1.85"

[dev-dependencies]
trybuild = "1.0.18"

postgres-types = { path = "../postgres-types", features = ["derive"] }
postgres = { path = "../postgres" }
